2021-09-17 11:08:52 [31merror[39m: uncaughtException: require(...) is not a function
TypeError: require(...) is not a function
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:26
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/lib/sequelize.js:53:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/app.js:14:19)
2021-09-17 11:10:29 [31merror[39m: uncaughtException: Cannot read properties of undefined (reading 'define')
TypeError: Cannot read properties of undefined (reading 'define')
    at module.exports (/home/prashant/Documents/node.js/node-framework/database/models/internal-user/privilege.model.js:2:20)
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:26
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/lib/sequelize.js:53:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
2021-09-17 11:12:58 [31merror[39m: uncaughtException: Unexpected token 'export'
/home/prashant/Documents/node.js/node-framework/database/models/internal-user/privilege.model.js:1
export default (sequelize, datatypes) => {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:3
    at Array.forEach (<anonymous>)
2021-09-17 11:14:19 [31merror[39m: uncaughtException: Cannot read properties of undefined (reading 'define')
TypeError: Cannot read properties of undefined (reading 'define')
    at module.exports (/home/prashant/Documents/node.js/node-framework/database/models/internal-user/privilege.model.js:2:20)
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:26
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/lib/sequelize.js:53:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
2021-09-17 11:14:51 [31merror[39m: uncaughtException: Cannot read properties of undefined (reading 'define')
TypeError: Cannot read properties of undefined (reading 'define')
    at module.exports (/home/prashant/Documents/node.js/node-framework/database/models/internal-user/privilege.model.js:2:20)
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:26
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/lib/sequelize.js:53:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
2021-09-17 11:15:05 [31merror[39m: uncaughtException: Cannot read properties of undefined (reading 'define')
TypeError: Cannot read properties of undefined (reading 'define')
    at module.exports (/home/prashant/Documents/node.js/node-framework/database/models/internal-user/privilege.model.js:2:20)
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:26
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/lib/sequelize.js:53:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
2021-09-17 11:15:37 [31merror[39m: uncaughtException: require(...) is not a function
TypeError: require(...) is not a function
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:26
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/lib/sequelize.js:53:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/app.js:14:19)
2021-09-17 11:17:27 [31merror[39m: uncaughtException: require(...) is not a function
TypeError: require(...) is not a function
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:21
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/lib/sequelize.js:53:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/app.js:14:19)
2021-09-17 11:20:03 [31merror[39m: uncaughtException: require(...) is not a function
TypeError: require(...) is not a function
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:21
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/lib/sequelize.js:53:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/app.js:14:19)
2021-09-17 11:27:31 [31merror[39m: uncaughtException: require(...) is not a function
TypeError: require(...) is not a function
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:21
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/lib/sequelize.js:53:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/app.js:14:19)
2021-09-17 11:37:13 [31merror[39m: uncaughtException: require(...) is not a function
TypeError: require(...) is not a function
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:35
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/lib/sequelize.js:53:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/app.js:14:19)
2021-09-17 11:38:07 [31merror[39m: uncaughtException: require(...) is not a function
TypeError: require(...) is not a function
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:35
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/lib/sequelize.js:53:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/app.js:14:19)
2021-09-17 11:40:21 [31merror[39m: uncaughtException: Unrecognized datatype for attribute "role_privileges.privilegeId"
Error: Unrecognized datatype for attribute "role_privileges.privilegeId"
    at /home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:1001:15
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13469:38
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13468:7)
    at Function.init (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:997:28)
    at Sequelize.define (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/sequelize.js:440:11)
    at module.exports (/home/prashant/Documents/node.js/node-framework/database/models/internal-user/rolePrivilege.model.js:2:20)
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:35
    at Array.forEach (<anonymous>)
2021-09-17 11:41:08 [31merror[39m: uncaughtException: Unrecognized datatype for attribute "role_privileges.privilegeId"
Error: Unrecognized datatype for attribute "role_privileges.privilegeId"
    at /home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:1001:15
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13469:38
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13468:7)
    at Function.init (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:997:28)
    at Sequelize.define (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/sequelize.js:440:11)
    at module.exports (/home/prashant/Documents/node.js/node-framework/database/models/internal-user/rolePrivilege.model.js:2:26)
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:35
    at Array.forEach (<anonymous>)
2021-09-17 11:41:26 [31merror[39m: uncaughtException: Unrecognized datatype for attribute "role_privileges.privilegeId"
Error: Unrecognized datatype for attribute "role_privileges.privilegeId"
    at /home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:1001:15
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13469:38
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13468:7)
    at Function.init (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:997:28)
    at Sequelize.define (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/sequelize.js:440:11)
    at module.exports (/home/prashant/Documents/node.js/node-framework/database/models/internal-user/rolePrivilege.model.js:2:20)
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:35
    at Array.forEach (<anonymous>)
2021-09-17 11:41:38 [31merror[39m: uncaughtException: Unrecognized datatype for attribute "role_privileges.privilegeId"
Error: Unrecognized datatype for attribute "role_privileges.privilegeId"
    at /home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:1001:15
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13469:38
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13468:7)
    at Function.init (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:997:28)
    at Sequelize.define (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/sequelize.js:440:11)
    at module.exports (/home/prashant/Documents/node.js/node-framework/database/models/internal-user/rolePrivilege.model.js:2:26)
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:35
    at Array.forEach (<anonymous>)
2021-09-17 11:42:10 [31merror[39m: uncaughtException: Unrecognized datatype for attribute "role_privileges.privilegeId"
Error: Unrecognized datatype for attribute "role_privileges.privilegeId"
    at /home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:1001:15
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13469:38
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13468:7)
    at Function.init (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:997:28)
    at Sequelize.define (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/sequelize.js:440:11)
    at module.exports (/home/prashant/Documents/node.js/node-framework/database/models/internal-user/rolePrivilege.model.js:2:26)
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:35
    at Array.forEach (<anonymous>)
2021-09-17 11:43:02 [31merror[39m: uncaughtException: Unrecognized datatype for attribute "role_privileges.privilegeId"
Error: Unrecognized datatype for attribute "role_privileges.privilegeId"
    at /home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:1001:15
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13469:38
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13468:7)
    at Function.init (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:997:28)
    at Sequelize.define (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/sequelize.js:440:11)
    at module.exports (/home/prashant/Documents/node.js/node-framework/database/models/internal-user/rolePrivilege.model.js:2:26)
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:35
    at Array.forEach (<anonymous>)
2021-09-17 11:43:21 [31merror[39m: uncaughtException: Unrecognized datatype for attribute "role_privileges.privilegeId"
Error: Unrecognized datatype for attribute "role_privileges.privilegeId"
    at /home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:1001:15
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13469:38
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13468:7)
    at Function.init (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:997:28)
    at Sequelize.define (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/sequelize.js:440:11)
    at module.exports (/home/prashant/Documents/node.js/node-framework/database/models/internal-user/rolePrivilege.model.js:2:26)
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:35
    at Array.forEach (<anonymous>)
2021-09-17 11:43:37 [31merror[39m: uncaughtException: Unrecognized datatype for attribute "role_privileges.privilegeId"
Error: Unrecognized datatype for attribute "role_privileges.privilegeId"
    at /home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:1001:15
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13469:38
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13468:7)
    at Function.init (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:997:28)
    at Sequelize.define (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/sequelize.js:440:11)
    at module.exports (/home/prashant/Documents/node.js/node-framework/database/models/internal-user/rolePrivilege.model.js:2:26)
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:35
    at Array.forEach (<anonymous>)
2021-09-17 11:43:49 [31merror[39m: uncaughtException: Unrecognized datatype for attribute "role_privileges.privilegeId"
Error: Unrecognized datatype for attribute "role_privileges.privilegeId"
    at /home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:1001:15
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13469:38
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13468:7)
    at Function.init (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:997:28)
    at Sequelize.define (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/sequelize.js:440:11)
    at module.exports (/home/prashant/Documents/node.js/node-framework/database/models/internal-user/rolePrivilege.model.js:2:26)
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:35
    at Array.forEach (<anonymous>)
2021-09-17 11:44:02 [31merror[39m: uncaughtException: Unrecognized datatype for attribute "role_privileges.privilegeId"
Error: Unrecognized datatype for attribute "role_privileges.privilegeId"
    at /home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:1001:15
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13469:38
    at /home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (/home/prashant/Documents/node.js/node-framework/node_modules/lodash/lodash.js:13468:7)
    at Function.init (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/model.js:997:28)
    at Sequelize.define (/home/prashant/Documents/node.js/node-framework/node_modules/sequelize/lib/sequelize.js:440:11)
    at module.exports (/home/prashant/Documents/node.js/node-framework/database/models/internal-user/rolePrivilege.model.js:2:26)
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:35
    at Array.forEach (<anonymous>)
2021-09-17 15:07:47 [31merror[39m: uncaughtException: Assignment to constant variable.
TypeError: Assignment to constant variable.
    at module.exports (/home/prashant/Documents/node.js/node-framework/database/models/internal-user/rolePrivileges.model.js:15:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2021-09-17 15:39:20 [31merror[39m: uncaughtException: require(...) is not a function
TypeError: require(...) is not a function
    at /home/prashant/Documents/node.js/node-framework/lib/sequelize.js:56:21
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/lib/sequelize.js:53:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/app.js:14:19)
2021-09-17 16:37:51 [31merror[39m: uncaughtException: Unexpected token '}'
/home/prashant/Documents/node.js/node-framework/database/models/internal-user/rolePrivilege.model.js:7
    },
    ^

SyntaxError: Unexpected token '}'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/prashant/Documents/node.js/node-framework/database/models/internal-user/privilege.model.js:1:23)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
